services:
  my-jekyll-container:
    build: 
      dockerfile: Dockerfile
    container_name: local_jekyll
    tty: true
    volumes:
      - .:/app
    ports:
      - "4000:4000"
      - "4001:4001"
    command: >
      bash -c "bundle install
      && bundle exec jekyll serve --force_polling -H 0.0.0.0 -P 4000 --livereload --livereload_port 4001"